Play travis
Otus-DevOps-2020-08/BolotNam_infra pull request #1
Opened 2020-09-16 19:18 UTC by BolotNam

2020-09-17 05:52 UTC, mrgreyves requested changes
Здравствуйте!) Проверил ваше дз. Оставил комментарии к файлам. Тесты тревиса не работают, постарайтесь их починить. ДЗ возвращаю на доработку.

2020-09-17 05:52 UTC, mrgreyves commented on .github/PULL_REQUEST_TEMPLATE_2.md
> +# Выполнено ДЗ №
Лишний файлик =)

2020-09-17 05:52 UTC, mrgreyves commented on play-travis/test.py
> +import unittest
Ошибка

2020-09-17 10:08 UTC, BolotNam commented on play-travis/test.py
> +import unittest
а не подскажите решение ?
вроде все сделал, но в конце не приходит сообщение в slack от TravisCI, как показано в ДЗ

2020-09-17 10:08 UTC, BolotNam commented on play-travis/test.py
> +import unittest
файлик удалил

2020-09-17 14:27 UTC, BolotNam commented on play-travis/test.py
> +import unittest
Исправил test.py

2020-09-18 05:35 UTC, mrgreyves requested changes
Здравствуйте!) Проверил ваше дз. Нужно добавить описание к пр, так же тесты тревиса не запуска.тся, стоит обратить на это внимание. ДЗ возвращаю на доработку.
![image](https://user-images.githubusercontent.com/34331259/93560082-ebcae580-f989-11ea-9f57-4ae813fbb018.png)

2020-09-19 09:35 UTC, BolotNam commented
Прошу принять ДЗ 2.
Вроде все сделал ))

2020-09-20 15:32 UTC, mrgreyves approved these changes
Здравствуйте!) Вот теперь все хорошо. Не забывайте про описание к вашим пр =)

2020-09-20 17:28 UTC, merged