Cloud testapp
Otus-DevOps-2020-08/BolotNam_infra pull request #3
Opened 2020-09-23 20:11 UTC by BolotNam

# Выполнено ДЗ №4

 - [x] Основное ДЗ

## В процессе сделано:
 - Пункт 1
        - установлена и настроена консоль YC
 - Пункт 2
        - создан скрипт install_ruby.sh
        - создан скрипт install_mongodb.sh
        - создан скрипт deploy.sh
        - создан metadata.yaml
#№ Создание ВМ
yc compute instance create \
  --name reddit-app-2 \
  --hostname reddit-app-2 \
  --memory=4 \
  --create-boot-disk image-folder-id=standard-images,image-family=ubuntu-1604-lts,size=10GB \
  --network-interface subnet-name=default-ru-central1-a,nat-ip-version=ipv4 \
  --metadata serial-port-enable=1 \
  --metadata-from-file user-data=./metadata.yaml

## Как проверить работоспособность:
 - http://84.201.172.198:9292/

## PR checklist
 - [cloud-testapp] 
 - [ YC]

2020-09-24 05:45 UTC, mrgreyves requested changes
Здравствуйте!) Проверил ваше дз. Проверьте стоит ли флаг -х на скриптах, так же проверьте как устанавливается ruby. ДЗ возвращаю на доработку.

2020-09-24 19:28 UTC, BolotNam commented
All test passed

2020-09-25 09:00 UTC, mrgreyves approved these changes
Здравствуйте!) Апрув!)

2020-09-25 09:02 UTC, mrgreyves commented
Оууу! У вас образовался небольшой конфликт в ридми. Надеюсь особых проблем возникнуть не должно =)

2020-09-25 19:12 UTC, merged